# Generated by Django 5.1 on 2024-08-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=15)),
                ('confirm_password', models.TextField(max_length=15)),
            ],
        ),
    ]
