# Generated by Django 5.1 on 2024-08-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='confirm_password',
            new_name='cpass',
        ),
    ]
